parameters:
#    mysite_blog.example.class: Mysite\HomeBundle\Example

services:
#    mysite_blog.example:
#        class: %mysite_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    mysite_home.twig.extension:
        class: Mysite\HomeBundle\Twig\Extensions\MysiteHomeExtension
        tags:
            - { name: twig.extension }
