parameters:
#    blogger_blog.example.class: Mysite\HomeBundle\Example

services:
    mysite_home.twig.extension:
        class: Mysite\HomeBundle\Twig\Extensions\MysiteHomeExtension
        tags:
            - { name: twig.extension }
